### PR TITLE
Move `.nojekyll` to playbook repo

### PR DESCRIPTION
**Pull request by krisstern**
## Tasks completed
1. Added `working-directory` to `.github/workflows/publish.yml`
2. Moved `.nojekyll` to serving directory at `playbook-repo` directory
3. Added override for `glob-parent` package to get rid of known vulnerabilities.

### CODE REVIEW

**Comment by Vandit1604** [comment]
Hey kris, Is this working locally on your machine?

**Comment by krisstern** [comment]
There is no way to check locally, since it is supposed to only work via GitHub Actions. 
So it is just trial and error until it works.

**Comment by krisstern** [comment]
Or you could just push to try different fixes until it works.

**Comment by Vandit1604** [comment]
my bad! I thought you have tested this on your setup from what i read in your message.

**Comment by krisstern** [comment]
I have tested the individual command(s) in each part of the action, but not the whole GitHub Action itself locally.

**Pull request merged**
