### PR TITLE
Fix UI Project Dependency and Gulp related errors

### PR DESCRIPTION
**Pull request by Vandit1604**
I have ported all the changes we did to a fresh fork of Antora UI Project since we updated the package.json and package-lock.json so much that it became a mess
If this PR broke more than fixing , please disregard

### CODE REVIEW

**Comment by krisstern** [comment]
@Vandit1604 Before I merge this, could you please tell me what all these newly added HTML files are for?

**Comment by Vandit1604** [comment]
@krisstern Those are from `playbook-repo/build`
That's odd because I added their path in .gitignore

**Comment by Vandit1604** [comment]
@krisstern Maybe after merging we can face some deployment issues . maybe

**Comment by krisstern** [comment]
Let's merge it now, but prepared to revert if anything bad happens

**Review by krisstern — APPROVED** [review]

**Pull request merged**
